const { all } = require("core-js/fn/promise")

LISTEN = "pages/ascolta"

function getPath1() {
    return [
        LISTEN,
        "pages/elem/quiz1",
        "pages/elem/quiz2",
        LISTEN,
        "pages/elem/quiz3",
        "pages/elem/scacchiera_vuota",
        "pages/elem/battaglia_navale",
        "pages/ascolta_torre", // Torre
        "pages/torre_help",
        "pages/elem/gioco1",
        "pages/elem/img_gioco1",
        "pages/elem/quiz4",
        "pages/elem/quiz5",
        "pages/elem/quiz6",
        "pages/elem/quiz7",
        "pages/elem/img_1",
        "pages/elem/gioco2",
        "pages/elem/gioco3",
        "pages/elem/gioco4",
        "pages/elem/quiz8",
        LISTEN,
        "pages/elem/gioco5",
        "pages/elem/img_gioco5",
        "pages/elem/gioco6",
        "pages/elem/img_gioco6",
        "pages/ascolta_alfiere", // Alfiere
        "pages/elem/gioco7",
        "pages/elem/img_gioco7",
        "pages/elem/quiz9",
        "pages/elem/quiz10",
        "pages/elem/quiz11",
        "pages/elem/quiz12",
        "pages/elem/quiz13",
        "pages/elem/gioco8",
        "pages/elem/gioco9",
        LISTEN,
        "pages/elem/quiz14",
        "pages/elem/gioco10",
        "pages/elem/img_gioco10",
        "pages/elem/gioco11",
        "pages/elem/img_gioco11",
        "pages/elem/img_allsquare",
        "pages/elem/quiz15",
        LISTEN,
        "pages/elem/quiz16",
        "pages/classifica",
        "pages/endpage"
    ]
}

function getPath2() {
    return [
        LISTEN,
        "pages/med/quiz1",
        LISTEN,
        "pages/med/quiz2",
        "pages/elem/scacchiera_vuota",
        "pages/ascolta_torre", // Torre
        "pages/torre_help",
        "pages/med/gioco1",
        "pages/med/img_gioco1",
        "pages/med/quiz3",
        "pages/med/quiz4",
        "pages/med/quiz5",
        "pages/med/quiz6",
        "pages/med/img_1",
        "pages/med/gioco2",
        "pages/med/gioco4",
        "pages/med/quiz7",
        LISTEN,
        "pages/med/gioco5",
        "pages/med/img_gioco5",
        "pages/med/gioco6",
        "pages/med/img_gioco6",
        "pages/ascolta_alfiere", // Alfiere
        "pages/med/gioco7",
        "pages/med/img_gioco7",
        "pages/med/gioco8",
        "pages/med/quiz8",
        "pages/med/quiz9",
        "pages/med/quiz10",
        LISTEN,
        "pages/med/quiz11",
        "pages/elem/img_gioco10",
        "pages/med/gioco11b",
        "pages/med/img_gioco11b",
        "pages/elem/img_allsquare",
        "pages/ascolta_cavallo", // CAVALLO
        "pages/med/img_cavallo",
        "pages/med/gioco_spirit",
        "pages/med/img_spirit",
        "pages/med/gioco13b",
        "pages/med/gioco13b_soluzione",
        "pages/med/gioco12b",
        "pages/med/gioco12b_soluzione",
        LISTEN,
        "pages/med/quiz14",
        LISTEN,
        "pages/med/quiz16",
        "pages/classifica",
        "pages/endpage"
    ]
}

function getPath3() {
    return [
        LISTEN,
        "pages/ascolta_torre",
        "pages/lic/img_gioco1",
        "pages/lic/quiz1",
        "pages/lic/quiz2",
        "pages/lic/img_1",
        "pages/lic/gioco2",
        "pages/lic/gioco4",
        "pages/lic/quiz7",
        LISTEN,
        "pages/lic/gioco5",
        "pages/lic/img_gioco5",
        "pages/lic/gioco6",
        "pages/lic/img_gioco6",
        "pages/ascolta_alfiere", // Alfiere
        "pages/lic/img_gioco7",
        "pages/lic/gioco8",
        "pages/lic/quiz8",
        "pages/lic/quiz9",
        "pages/lic/quiz10",
        LISTEN,
        "pages/lic/quiz11",
        "pages/lic/img_gioco10",
        "pages/lic/gioco11b",
        "pages/lic/img_gioco11b",
        "pages/lic/img_allsquare",
        "pages/ascolta_cavallo", // CAVALLO
        "pages/lic/img_cavallo",
        "pages/lic/gioco_spirit",
        "pages/lic/img_spirit",
        "pages/lic/gioco13b",
        "pages/lic/gioco13b_soluzione",
        "pages/lic/gioco12b",
        "pages/lic/gioco12b_soluzione",
        "pages/lic/gioco14",
        "pages/lic/gioco15",
        "pages/lic/img_gioco15",
        "pages/ascolta_regina",
        "pages/lic/img_regina",
        "pages/lic/gioco16",
        "pages/lic/img_gioco16",
        "pages/lic/gioco17",
        //"pages/lic/gioco18",
        LISTEN,
        "pages/lic/gioco_training_toro",
        "pages/lic/gioco_toro",
        "pages/lic/gioco_toro1",
        "pages/lic/gioco_toro2",
        LISTEN, // da fare da qui in avanti per i quiz
        "pages/lic/quiz14",
        //LISTEN,
        //"pages/lic/quiz16",
        "pages/classifica",
        "pages/endpage"
    ]
}

function getPath4() {
    return [
        LISTEN,
        "pages/natale/ascolta_torre",
        "pages/natale/img_gioco1",
        "pages/natale/quiz1",
        "pages/natale/quiz2",
        "pages/natale/img_1",
        "pages/natale/gioco2",
        "pages/natale/gioco4",
        "pages/natale/quiz7",
        LISTEN,
        "pages/natale/gioco5",
        "pages/natale/img_gioco5",
        "pages/natale/gioco6",
        "pages/natale/img_gioco6",
        "pages/ascolta_alfiere", // Alfiere
        "pages/natale/img_gioco7",
        "pages/natale/gioco8",
        "pages/natale/quiz8",
        "pages/natale/quiz9",
        "pages/natale/quiz10",
        LISTEN,
        "pages/natale/quiz11",
        "pages/natale/img_gioco10",
        "pages/natale/gioco11b",
        "pages/natale/img_gioco11b",
        "pages/natale/img_allsquare",
        "pages/ascolta_cavallo",// CAVALLO
        "pages/natale/img_cavallo",
        "pages/natale/gioco_spirit",
        "pages/natale/img_spirit",
        "pages/natale/gioco13b",
        "pages/natale/gioco13b_soluzione",
        "pages/natale/gioco12b",
        "pages/natale/gioco12b_soluzione",
        "pages/natale/gioco14",
        "pages/natale/gioco15",
        "pages/natale/img_gioco15",
        "pages/ascolta_regina",
        "pages/natale/img_regina",
        "pages/natale/gioco16",
        "pages/natale/img_gioco16",
        "pages/natale/gioco17",
        //"pages/natale/gioco18",
        "pages/natale/gioco19",
        LISTEN,
        "pages/natale/gioco_training_toro",
        "pages/natale/gioco_toro",
        "pages/natale/gioco_toro1",
        "pages/natale/gioco_toro2",
        LISTEN, // da fare da qui in avanti per i quiz
        "pages/natale/quiz14",
        //LISTEN,
        //"pages/natale/quiz16",
        "pages/classifica",
        "pages/endpage"
    ]
}

allpages = {
    "path_1": getPath1(),
    "path_2": getPath2(),
    "path_3": getPath3(),
    "path_4": getPath4()

}
module.exports = {
    allpages: allpages
}